services:
  db:
    image: postgres:15-alpine
    container_name: asset_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: samar
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: asset_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
